### PR TITLE
Avl tree implementation (#198)

### PR DESCRIPTION
**Pull request by muneeb20**
Implementation of Avl tree

Notes:
Test cases will be added in another branch
Recommend any other methods I need to put in

### CODE REVIEW

**Comment by danghai** [comment]
Hello @muneeb20 , thanks your PR. It is good to add test cases in same PR ( I mean same branch). Could you add test case ?

**Comment by muneeb20** [comment]
Sure @danghai sure let me add it.

**Comment by goswami-rahul** [comment]
@muneeb20 Are you going to add more tests in this same PR, or should I merge this?

**Comment by christianbender** [comment]
@goswami-rahul @danghai Should we create a new label ```on hold```?  Especial for this kind of PRs?

**Comment by keon** [comment]
@christianbender how about work in progress - `WIP` tag?
We could still use `on hold` for PRs that are actually not in development at the moment.

**Pull request merged**
