### PR TITLE
separate tests in array/ module

### PR DESCRIPTION
**Pull request by goswami-rahul**
- refer #162

### CODE REVIEW

**Comment by goswami-rahul** [comment]
whoops! I think Travis CI got triggered when I added test module. But it has not been setup properly yet to do check for unittests in Python3.6. @keon Please take a look.

**Comment by goswami-rahul** [comment]
Travis says:
```
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
The command "pip install -r requirements.txt" failed and exited with 1 during .
Your build has been stopped.
```
It needs a `requirements.txt` file, so I am adding one.

**Comment by goswami-rahul** [comment]
Yeah, Travis tests are working fine now!

**Comment by keon** [comment]
Awesome! @goswami-rahul  I added our repo to https://travis-ci.org/keon/algorithms to check & keep the quality. 
Thanks for the update.

**Comment by keon** [comment]
I think .cache should be added to .gitignore ?

**Comment by keon** [comment]
I merged `.travis.yml` with #168 
It should run both flake8 and pytest.

**Comment by keon** [comment]
I'll merge this despite the failed test because fixing all of them is not the scope of this PR.
Good work!

**Comment by goswami-rahul** [comment]
Thanks @keon . The tests failed because there are many errors in other modules that are yet to be tested.  
Travis will show Error in all further PRs until we first resolve all those errors which are currently known.

**Pull request merged**
