### PR TITLE
Changed prime test.py

### PR DESCRIPTION
**Pull request by christianbender**
I removed a unnecessary 'else'. And I added a test suite (unittest).

### CODE REVIEW

**Comment by keon** [comment]
@christianbender do you want to be a collaborator on this project?
Since you are building all test cases, you will eventually know every part of this project.
You are still recommended to post PR instead of directly committing since we all can review the code.

**Comment by goswami-rahul** [comment]
@keon I think it is good idea to have @christianbender as a collaborator. It will help to have some active collaborators, since I think @ankit167 is not active these days.

**Comment by christianbender** [comment]
@keon @goswami-rahul 
Yes, of course. I would like be a collaborator.

**Comment by keon** [comment]
@christianbender Welcome!! 👍 I just sent the invitation (https://github.com/keon/algorithms/invitations)

**Pull request merged**
