### PR TITLE
Python packaging locally

### PR DESCRIPTION
**Pull request by danghai**
PR to make python packaging locally. 
I write the `setup.py` file. It successful install after command `sudo pip install .`. Unfortunately, I cannot import the `algorithms` package. You can test by creating the file `test.py` with content:

```python
import algorithms
def main():
    my_list = [1, 8, 3, 5, 6]
    my_list = insertion_sort(my_list)
    print(my_list)
```

Error:
```
  File "test.py", line 1, in <module>
    import algorithms
ImportError: No module named 'algorithms'
```
Am I missing something? What do you think @keon , @goswami-rahul , @christianbender , @SaadBenn

### CODE REVIEW

**Comment by danghai** [comment]
I think it works!. I may mess up with `PATH`, it stores the package in `python2` instead of `python3`.  Could you (@keon , @goswami-rahul , @christianbender , @SaadBenn ) clone my branch and install by `sudo pip install . `, and then test with a test.py file in a different directory:. `test.py` : 

```python
from sort import merge_sort

if __name__ == "__main__":
    my_list = [1, 8, 3, 5, 6]
    my_list = merge_sort.merge_sort(my_list)
    print(my_list)
```
And use command `python3 test,py` to see we can import them or not? Thanks

**Comment by christianbender** [comment]
@danghai I copied the file ```setup.py``` in my local repository and run ```sudo pip install .``` in it.   
I get this:  
> The directory '/home/christian/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/christian/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/christian/Programmierung/GitHub/algorithms
Installing collected packages: algorithms
  Running setup.py install for algorithms ... done
Successfully installed algorithms-1.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by danghai** [comment]
Could you try with command `python` not `python3`. Does it work?

**Comment by danghai** [comment]
It works for python3 packaging locally. I am going to merge them. Lets check in `README`. Let me know if you see any errors

**Pull request merged**
