### PR TITLE
Add edit distance DP problem

### PR DESCRIPTION
**Pull request by vinceajcs**
(Put an `X` inside the `[ ]` to denote check mark `[X]`.)

- [ ] **If creating a new file :**
  - [ ] added links to it in the README files ?
  - [X] included tests with it ?
  - [X] added description (overview of algorithm, time and space compleixty, and possible edge case) in docstrings ?

- [ ] **if done some changes :**
  - [ ] wrote short description in the PR explaining what the changes do ?
  - [ ] Fixes #[issue number] if related to any issue

- [ ] **other**

### CODE REVIEW

**Comment by vinceajcs** [comment]
Thank you! There wasn't a test file for dp algorithms so I added one in the tests folder. I moved my test there and updated the edit distance file accordingly. Please let me know if I need to change anything else.

**Comment by vinceajcs** [comment]
@goswami-rahul just a friendly bump. I think I took care of the requested changes!

**Comment by keon** [comment]
@vinceajcs looks like unit tests are currently failing.
Could you check if they are passing in your local environment?

**Comment by vinceajcs** [comment]
@keon you're right; I'm sorry about that. When I try running the unit tests (like tests/test_dp.py), I get a ModuleNotFoundError: No module named 'algorithms'. I searched for a while to see if I could figure out why I get this error, but I can't seem to fix it (I tried adding an init file in the dp folder). Is there any chance you could help me out? I want to get this working.

**Comment by danghai** [comment]
Hi @vinceajcs  , you miss the `_init_` file. I help you fix it. Thanks contribution.
@keon It works okay now.

**Comment by vinceajcs** [comment]
@danghai thank you so much!

**Pull request merged**
