### PR TITLE
add problem in bit/ for #241

### PR DESCRIPTION
**Pull request by goswami-rahul**
add 3 files: (#241 )
- bit/flip_bit_longest_seq.py
- bit/count_flips_to_convert.py
- array/max_ones_index.py  

This PR should be merged after #239 is merged, to avoid merge conflicts in that PR.

### CODE REVIEW

**Comment by danghai** [comment]
@goswami-rahul , in README, we already move all test to tests folder. It should be under `tests` in README? I

**Comment by goswami-rahul** [comment]
@danghai I will fix these conflicts after some time. I am quite busy these days, my final exams going to start after this week :skull_and_crossbones: .

**Comment by danghai** [comment]
@goswami-rahul take your time, and good luck ! :)

**Comment by danghai** [comment]
I add some fundamental bit manipulation in PR #253. Review them when you have a chance too

**Comment by goswami-rahul** [comment]
reopened as #294 .

**Pull request closed without merging**
