### PR TITLE
added a comment to let beginners know about the assert function in python

### PR DESCRIPTION
**Pull request by tejas-kr**

### CODE REVIEW

**Comment by delirious-lettuce** [comment]
@tejas-kr ,

Is this really necessary?

**Comment by tejas-kr** [comment]
yes the beginners don't know about this assert statement

**Comment by mingrammer** [comment]
Well, I think it is unnecessary, because it is not about logic but just python grammar.

**Comment by keon** [comment]
I believe it is safe to assume that users know what assert is :)

**Comment by tejas-kr** [comment]
ok as you wish

**Pull request closed without merging**
