### PR TITLE
Create num_digits.py

### PR DESCRIPTION
**Pull request by vicky1999**
num_digits.py was created to find the  number of digits in a number using log10 method in math module.

### CODE REVIEW

**Comment by ericklarac** [comment]
Could you please add unittest? 

Follow this as a guide: https://github.com/keon/algorithms/pull/631/files

**Comment by CentralLT** [comment]
@vicky1999 ur working on @ericklarac request? maybe helpful to give other interested people a status update.

**Review by YoungMind44 — CHANGES_REQUESTED** [review]
```Python
if(__name__=='__main__'):
  num=input('Enter your number: ')
  print("Number of Digits in ",num," is : ",num_digits(num))
```
Please add unittest as well;

**Comment by vicky1999** [comment]
I have implementation and unit tests separately.  refer #740

**Pull request closed without merging**
