### PR TITLE
Add chinese remainder theorem

### PR DESCRIPTION
**Pull request by mansand1**
A solver for the chinese remainder theorem. 

Created with [Lazar](https://github.com/lazarko)

### CODE REVIEW

**Comment by mansand1** [comment]
Closes #757

**Comment by ericklarac** [comment]
Add your algorithm to the README file, please

**Comment by mansand1** [comment]
> Add your algorithm to the README file, please

Done! Thanks for the feedback.

**Comment by ericklarac** [comment]
LGTM, just update README in alphabetical order.

**Comment by mansand1** [comment]
> LGTM, just update README in alphabetical order.

Fixed it

**Pull request merged**
