### PR TITLE
Move all test into a folder

### PR DESCRIPTION
**Pull request by danghai**
PR to put all test into a folder `tests`. Enhance #29 
I think it is a great to put all test file into a folder named `tests`. 
Furthermore `pytest` in README does not work for me. It shows:
```
no test dir found testing here: /home/danghai/master/algorithms
*******************************************************************************
```
So, by putting all test file into a folder, I provide 2 ways to test in README instead. 
```
For running all tests write down:
    $ python3 -m unittest discover tests
For running some specific tests you can do this as following (Ex: sort):
    $ python3 -m unittest tests.test_sort
```
I already move all tests ( `linkedlist`, `sort`, `bit`) into tests folder. There are a lot of test for the rest of folder.  
What do you (@keon , @goswami-rahul , @christianbender , @SaadBenn ) think?

### CODE REVIEW

**Comment by keon** [comment]
awesome! I like this direction.

**Comment by danghai** [comment]
@goswami-rahul I think one of reason why I make the failure with `pytest` is PATH.  After command verson `pytest --version`: 
```
This is pytest version 3.5.0, imported from /usr/local/lib/python2.7/dist-packages/pytest.pyc
```

It should be inside python3.5. I am not sure how I can change the Path.

**Comment by danghai** [comment]
@goswami-rahul I think one of solution for this issue is to use command : `python3 -m pytest tests`.
Could you try it with command `python3 -m pytest array` ( Because you do not have tests folder yet)?

**Comment by danghai** [comment]
I am going to fix some others too

**Comment by danghai** [comment]
@goswami-rahul  I think it is good to merge now ?

**Pull request merged**
