### PR TITLE
Full binary tree from preorder and postorder

### PR DESCRIPTION
**Pull request by ShimoniSinha2019H1030019G**
I have created an implementation that constructs a full binary tree from given preorder and postorder traversals of the tree.
The file has been stored in the tree folder.

### CODE REVIEW

**Comment by ShimoniSinha2019H1030019G** [comment]
Can someone please comment and review/merge as soon as possible as this is a requirement for a course I am doing.

**Comment by ericklarac** [comment]
@ShimoniSinha2019H1030019G could you add some unit test under the test folder?

**Comment by ShimoniSinha2019H1030019G** [comment]
Hello @ericklarac I have created a new pull request  #736  for this code where I have added unit test also. (This was due to problem in my laptop).

Can you please check that and review/merge please.

Thanks.

**Comment by ericklarac** [comment]
> #736

Ok, will close this PR

**Pull request closed without merging**
