### PR TITLE
Add coverall to algorithms

### PR DESCRIPTION
**Pull request by danghai**
PR to add coverall to algorithms. 
test coverage is measurement to find how much of your codebase is covered by testing with the ultimate goal of making project 100% covered by tests. It does this by running all of your tests (unit tests) and keeping track of what lines of the project source code is executed and not executed while running your tests.
@christianbender : It has one issue in `prime_test`. Could you help me review it? I am not sure why it is missing n in parameter. btw, I fix a minor in your `test_math`. 
@keon , @goswami-rahul , @SaadBenn . What do you think? 
Look at this site for my repo about coverall:
https://coveralls.io/github/danghai/algorithms

### CODE REVIEW

**Comment by goswami-rahul** [comment]
Its weird, the tests are failing for `maths/prime_test` and `maths/prime_test2`. The error is:
```
=====================================================================
ERROR: tests.test_maths.prime_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
TypeError: prime_test() missing 1 required positional argument: 'n'
======================================================================
ERROR: tests.test_maths.prime_test2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
TypeError: prime_test2() missing 1 required positional argument: 'n'
```
But, both have been given correct argument in the tests.
It came up when `nosetests` are used. It works fine with `unittest` and `pytest`. I am not sure, but maybe `nosetest` has some syntax confusion due to the name `prime_test` has word **test** in it?? 
A possible solution is to rename `prime_test.py` -> `prime_check.py`. And same with the function names.

What do you say @danghai ?

**Comment by danghai** [comment]
@goswami-rahul Awesome, it is fixed! It may violate the name

**Comment by keon** [comment]
I love it

**Comment by goswami-rahul** [comment]
@danghai great! The error is resolved.

**Pull request merged**
