### PR TITLE
[Work in Progress] reorganization (#278)

### PR DESCRIPTION
**Pull request by keon**
#278
I was working to change everything at once until realized that this is too much change.
So I am committing the changes one piece at a time to this PR.

For every categories below, I am doing the following:
- putting every files inside `algorithms` folder
- changing some names of files and algorithms
- updating tests

- [x] arrays
- [x] backtrack
- [x] bfs
- [x] dfs
- [x] dp
- [x] graph
- [x] heap
- [x] linkedlist
- [x] map
- [x] maths
- [x] matrix
- [x] queues
- [x] search
- [x] set
- [x] sort
- [x] stack
- [x] strings

### CODE REVIEW

**Comment by goswami-rahul** [comment]
@keon maybe we could have a separate branch for these changes, since these will be too much? And we can merge it once its done.

**Comment by danghai** [comment]
@keon I will look at it

**Comment by danghai** [comment]
@keon I have updated all reorganization in source code. Lets review them!

**Comment by keon** [comment]
thanks @danghai ! I've been working on cleaning, too. let me commit those and finally merge this to the main branch

**Comment by danghai** [comment]
@keon Thanks. I am going to update links in `README.md` too

**Comment by keon** [comment]
@danghai @goswami-rahul @christianbender @SaadBenn @ankit167 
Since this repo is moving faster than my editing speed, and other PRs might depend on this one,
I will merge this PR now and post another PR regarding cleanup.

**Pull request merged**
