### PR TITLE
add_top_1_dp

### PR DESCRIPTION
**Pull request by edwardw1987**
(Put an `X` inside the `[ ]` to denote check mark `[X]`.)

- [ ] **If creating a new file :**
  - [ ] added links to it in the README files ?
  - [ ] included tests with it ?
  - [ ] added description (overview of algorithm, time and space compleixty, and possible edge case) in docstrings ?

- [ ] **if done some changes :**
  - [ ] wrote short description in the PR explaining what the changes do ?
  - [ ] Fixes #[issue number] if related to any issue

- [ ] **other**

### CODE REVIEW

**Comment by goswami-rahul** [comment]
Hi! Sorry for late response. Can you please explain what your algorithm is doing and also rename it and save as some descriptive name with explainations? Thanks.

**Comment by edwardw1987** [comment]
Hi, my algorithm is another solution to the arrays problem `top 1`, which 
counting elements and updating the result during once iteration. Comparing with the available solution, I think it will be more efficient.

**Comment by keon** [comment]
@edwardw1987 why did you close this PR?

**Comment by edwardw1987** [comment]
Hi, Keno
    It's superised to catch your message!
    The project you launched is really cool and awesome. 
    I am a python developer who has been interested in algorithm, but I didn't find a right way to contribute code snippets. (my first pull request)
    Sorry for the closing!

**Pull request closed without merging**
