### PR TITLE
Created CONTRIBUTING_KR.md in Korean

### PR DESCRIPTION
**Pull request by aig031**
I translate CONTRIBUTE.md to CONTRIBUTE_KR.md

### CODE REVIEW

**Comment by lg970325** [comment]
README in Korean will be ready soon!

**Comment by aig031** [comment]
Are there any additional requirements needed?

**Comment by keon** [comment]
Korean translation doesn't sound right, did you use Google translate or something similar?

**Comment by aig031** [comment]
I translated it without using translator app. I felt sorry that you find some mistranslations on CONTIBUTING_KR.md. 
For my reconsideration if you don't mind, please tell me examples of mistranslations.

**Comment by keon** [comment]
@aig031 sorry about that. I just felt the Korean was in 'translation style', which happens when you translate languages word by word. This is not exactly a problem, as people can still understand. But I would suggest a few changes.

For example,

- *저희는 누구나로부터의 pull request도 환영할 준비가 되어있습니다.* -> 모든 Pull Request는 환영입니다. 
- *그리고 당신의 변화들을 만들기 위한 branch를 만들어주세요. 예를 들어* -> 그리고 새로운 내용을 더할 branch를 만들어주세요
- *repo에 새로운 알고리즘들을 성립하세요.* -> 새로운 알고리즘을 구현해주세요

**Comment by aig031** [comment]
Thanks for examples, now I recognize what you mean! I will change what you said soon, and check if there was some other sentence looks bit strange again. 
And of course, we'll update our link on README before request!

**Comment by aig031** [comment]
I reflect your examples and I also changed some sentences which can be read bit strange. I thought it is quite readable now.

**Comment by lg970325** [comment]
@danghai , it seems like #297 updated the link as you reorganized!

**Comment by danghai** [comment]
@lg970325 Yeah. But we need to confirm the translation.

**Comment by keon** [comment]
I approve the Korean translation.
Thanks!

**Pull request merged**
