### PR TITLE
Separate test for linkedlist, enhance and add some problem

### LINKED ISSUE #162: separate test module
Since we now have tests in most of the algorithms, I think it is a good idea to have a separate `test_module.py` file in each module. We can move all the tests from one module to it, and any further algorithms must have their tests in this file. It will make the repo easy to manage.
@keon what do you think? I can start working on this.

### PR DESCRIPTION
**Pull request by danghai**
PR for separating test for linkedlist.
Fix #162 
I write a function convert from `Node` to `list` for testing. Now, we can use `assertEqual` in unittest. There are still some test case that need to be added. 
I am going to add some problem relating to them too. It is first draft, please review them.
@keon , @goswami-rahul

### CODE REVIEW

**Comment by christianbender** [comment]
@danghai  super! I merge this PR.

**Comment by goswami-rahul** [comment]
@christianbender I think @danghai  was going to add more commits to this PR.

**Comment by christianbender** [comment]
@danghai damn!

**Comment by danghai** [comment]
@christianbender ,  It is fine. I create another PR then

**Pull request merged**
